[supervisord]
nodaemon=true

[program:web]
command=/bin/sh -c 'gunicorn rendi_backend.wsgi:application --bind 0.0.0.0:$PORT'
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A rendi_backend worker --loglevel=info
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0