[supervisord]
nodaemon=true

[program:web]
command=gunicorn rendi_backend.wsgi:application --bind 0.0.0.0:$PORT
directory=/opt/render/project/src
autostart=true
autorestart=true

[program:celery]
command=celery -A rendi_backend worker --loglevel=info
directory=/opt/render/project/src
autostart=true
autorestart=true