# Generated by Django 4.2.28 on 2026-03-31 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_property_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_commitments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_ccj', models.BooleanField(blank=True, null=True)),
                ('has_missed_payments', models.BooleanField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('time_estimate', models.CharField(max_length=100)),
                ('deposit_needed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_gap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_months', models.PositiveSmallIntegerField()),
                ('breakdown', models.JSONField(default=dict)),
                ('action_plan', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
