# Generated by Django 5.1.7 on 2026-04-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='biggest_blocker',
            field=models.CharField(default='deposit', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='blocker_priority',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='simulations',
            field=models.JSONField(default=list),
        ),
    ]
