# Generated by Django 6.0.4 on 2026-04-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_biggest_blocker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='affordability_gap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='borrowing_power',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
