# Generated by Django 5.0.14 on 2026-04-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_assessment_biggest_blocker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome'), ('results', 'Results'), ('reminder_7', '7-day reminder'), ('reminder_14', '14-day reminder'), ('reminder_30', '30-day re-engagement'), ('progress', 'Progress update'), ('deposit_blocker', 'Deposit blocker'), ('fastest_improvement', 'Fastest improvement'), ('near_ready', 'Near ready'), ('advisor_ready', 'Advisor ready'), ('advisor_followup', 'Advisor follow-up')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_type', 'sent_at'], name='emails_emai_user_id_35e39f_idx')],
            },
        ),
    ]
